name: dough
description: Widgets for a smooshy UI.
version: 0.0.1
repository: https://github.com/HatFeather/flutter_dough
homepage: https://hatfeather.io/

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
