name: dough_sensors
description: This library provides smooshy gyro widgets.
version: 0.0.1
repository: https://github.com/josiahsrc/dough/tree/master/packages/dough_sensors
homepage: https://josiahsaunders.com/
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dough:
    path: ../dough
  sensors: ^2.0.0
  equatable: ^2.0.0
  vector_math: ^2.1.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.0.0
